theme: just-the-docs
markdown: kramdown
title: Notes
description: Timeless Notes
url: https://notes.wellosoft.net
collections:
  articles:
    permalink: "/:path/"
    output: true
just_the_docs:
  collections:
    articles:
      name: Artikel